### PR TITLE
Added support for 6 new fonts

### PR DESCRIPTION
**Pull request by edwinb24**
Firstly, thanks for the amazing package!
I added support for fonts: Great Vibes, Josefin Sans, Lobster, Rakkas, Raleway, Raleway Black, Raleway Extra Bold, Raleway Extra Thin, Raleway Thin, Srisakdi. I read the contributors guide too late for my first commit, but after made a 2nd commit with the corrected guidelines. I added a little of more crazy fonts with the idea of using them together with other fonts. Let me know if you want me to make any changes.

P.S. I was going to add Celestia Antiqua and Calibri too, but I couldn't find their Licenses anywhere... Any idea of where I could look for them?

### CODE REVIEW

**Comment by lierdakil** [comment]
Hi. Thanks for your work. However, I'm a bit confused. The primary purpose of this package is to let users try out monospace fonts they can use with the Atom editor. And some (if not all) of the fonts you're adding here are decidedly not monospace. So... why do you want to add them here?

**Comment by edwinb24** [comment]
I was adding them with the intention of providing font that will allow users to customize the styles.less files easier in the case they want to use multiple fonts (https://www.screencast.com/t/clDOamBoQ ). But, you are right this seems out of the scope of the package.

**Comment by lierdakil** [comment]
> in the case they want to use multiple fonts

Still doesn't make much sense to me. Non-monospace fonts generally don't work well in an otherwise monospace text editor. Best case scenario, stuff ends up looking slightly misaligned (enough to be noticeable). Worst case, it looks like an OCD nightmare. Also, mixing fonts in general doesn't work all that well for the same reason.

So... yeah. Seems out of scope. Sorry if you feel like you wasted your time here. Good news is, you could easily create your own package based off this one with the fonts you like, if you wanted to.

Last point, which isn't relevant perhaps, but still. Celestia Antiqua and Calibri use rather restrictive proprietary licences, they can't be freely redistributed.

**Comment by edwinb24** [comment]
Thanks for the feedback, lierdakil. No, I don't feel I wasted my time, it was a cool mini-project to work on yesterday, I ended up with a cool looking local environment 😎, and learning a lot about developing packages for Atom. If I get the chance I will definitely look more in-depth into creating packages. Thanks again for the amazing package, and all the good feedback! Keep up the awesome work!

**Pull request closed without merging**
