### PR TITLE
Fixups

### PR DESCRIPTION
**Pull request by lierdakil**
As discussed in https://github.com/atom-community/markdown-preview-plus/issues/402, here's a PR fixing some stuff I stumbled upon.

First and foremost, this is a re-write to align better with current Atom ecosystem and API. The API used has been around at least since 1.13.0, so Atom version bounds are not adjusted.

The code has been rewritten in (more or less) pure JavaScript instead of CoffeeScript. Mostly because I haven't written in CS for years, so it was just easier for me, but also because CS is kinda dying in general and within Atom ecosystem in particular.

What this rewrite does differently:

* Fixes config subscription disposal -- old code didn't properly dispose of config subscriptions
* Fixes extraneous calls to applyFont on activation -- old code called that thrice due to `atom.config.observe` triggering right away (unlike `atom.config.onDidChange`)
* Adds a new stylesheet via Atom's style manager, instead of setting the style attribute on the body element. I believe it's rather self-evident that setting `style` attribute on `body` is not very robust and can potentially lead to conflicts with other packages. Now the package uses the same method Atom itself does and sets the variable on `:root` instead of `body` (which is more or less [what Atom does](https://github.com/atom/atom/blob/e37413d18ed15c60c71b450c449eeadd73f4f9f2/static/text-editor.less#L5)). This particular change also fixes https://github.com/atom-community/markdown-preview-plus/issues/402
* Simplifies `fonts-fixer` element creation code
* Removes `fonts-fixer` element on deactivation

Additionally, it moves actual `atom-text-editor` style into it's own file, `main.less`, since otherwise it's included twice, once from `functions.less`, and once from `fonts.less`, which imports the former. Now `functions.less` only contains LESS functions and variables.

This is ready for review.

### CODE REVIEW

**Comment by braver** [comment]
Wow, thanks. I guess I'll have to spin up Atom and check it out.

Would you mind if I add you as a collaborator on the repo? It'll give you full access to make fixes and push releases.

**Comment by lierdakil** [comment]
> Would you mind if I add you as a collaborator on the repo?

I don't really mind, but here's a disclaimer: I have been roped into maintaining two projects this way already, and as a result, I kinda have my hands full as it is. So don't expect much activity from me.

**Comment by braver** [comment]
Well it's not so much about maintaining, but we're merging a bunch of stuff I didn't write and I like the idea that you might be able to go in an push a fix if the need arises. I already maintain enough stuff myself, so I know what it's like ;)

**Comment by lierdakil** [comment]
To be clear: are you OK with merging/releasing this, or do you want to test it first?

**Comment by lierdakil** [comment]
I did a few quick tests, and everything seems to be in order. But I'll keep using it for now in case I notice something misbehaving. Merging now, will push out a release next time I remember about it, probably after this weekend.

**Comment by braver** [comment]
🥇

**Pull request merged**
