### PR TITLE
Add mononoki from madmalik/mononoki

### PR DESCRIPTION
**Pull request by opatel99**
Earlier this week, I saw [Mononoki](https://github.com/madmalik/mononoki/) - "a font for programming and code review" - trending on [Hacker News](https://news.ycombinator.com/item?id=11716200).

As a fan of using monospace fonts while developing, I immediately turned to `fonts` in Atom to try it out. Since it had not been added and saw #24 in the Issues, I quickly spun up a PR to include Mononoki into the array of `fonts`.

Enjoy!

### CODE REVIEW

**Comment by troyharvey** [comment]
✊

**Comment by braver** [comment]
Awesome! Could you lowercase the file names and add a dash between "bold" and "italic" to keep it consistent?

**Comment by braver** [comment]
Oh, and while you're at it, please don't add -regular to the regular font.

**Comment by a7madgamal** [comment]
why didn't you tell me!
I just made the exact same font

**Comment by braver** [comment]
I totally missed that last commit in this PR.  ¯\_(ツ)_/¯

**Comment by kabarca1** [comment]
What happend here? Pull Request hijacking?

**Comment by braver** [comment]
Pull Request Pirating? 

No foul intentions on either side though. Just people (me mostly) not paying attention.

**Comment by a7madgamal** [comment]
no problem I'm glad people like my favourite font too 👍 
but It's amazing how you didn't notice! you even made the exact same comments on filenames etc.
I guess all developers have good processors with and bad memory lol

**Comment by braver** [comment]
No, I knew about this PR, but I thought it was stuck in the same state as yours and since you were responding quickly I figured we'd just run with that one. But apparently this PR actually was fixed already... either Github didn't mail me about it or I didn't flag it properly and forgot about it... Anyway, important thing is it's done.

**Pull request closed without merging**
