### PR TITLE
Generator

### PR DESCRIPTION
**Pull request by lierdakil**
I've had a couple hours to kill, so here goes...

This PR adds a generator script `scripts/gen.js` which updates `styles/fonts.less`, `package.json` and `README.md` based on fonts listed in `scripts/fonts.yaml`.

Pros:
-   Removed `functions.less`, as `fonts.less` can be generated as CSS directly
-   `fontFamily` config setting options are always sorted alphabetically
-   README always lists current fonts (also sorted alphabetically)
-   Some errors can be caught by the generator (e.g. #76)

Cons:
-   DevDependency on `js-yaml`

    Not a big deal, since it's only relevant for contributors, and not the end-user

-   Contributing is less intuitive

    Instead of modifying `fonts.less` and `package.json`, contributors will have to:
   
    1. Run `npm install --only=dev`
    2. Modify `scripts/fonts.yaml`
    3. Run `npm run build`

    Perhaps adding `CONTRIBUTING.md` and a PR template would be a good idea, but I'm running out of time.

Not a huge priority. Let me know what you think.

### CODE REVIEW

**Comment by braver** [comment]
Cool, that *should* make it a lot easier to work with, i.e. less easy to forget things. Some thoughts:

1. Do we need that build step to happen design time, or is there a post-install hook in Atom that we can run this on? I haven't looked at the API for a few years so I don't know what's possible, but I think that should be possible. 
2. Contributing is less intuitive, but it's easy enough to understand and review. Also not that many new fonts in a given year so 🤷‍♂️ 
3. Can we use JSON instead of YAML? I like YAML as much as the next guy, but since we just switched to regular old JavaScript it makes sense to use a data storage language JS can work with natively. Not that the data structure is super complex. And it saves us a dependency and might make it easier to do number 1.

**Comment by lierdakil** [comment]
> Do we need that build step to happen design time, or is there a post-install hook in Atom that we can run this on?

Technically, there is. But in my experience it tends to create more problems than it's worth it.

> Can we use JSON instead of YAML?

Yes, but I don't really want to. Reason is: YAML is much more forgiving, syntax-wise. JSON isn't that much fun to write by hand.

**Comment by braver** [comment]
Well, this isn't so bad to write though is it? You just copy paste it a bunch.

```json
{
	"Anonymous Pro": {
		"bold-italic": "anonymous-pro/anonymous-pro-bold-italic.ttf",
		"bold": "anonymous-pro/anonymous-pro-bold.ttf",
		"italic": "anonymous-pro/anonymous-pro-italic.ttf",
		"normal": "anonymous-pro/anonymous-pro.ttf"
	},
	"Aurulent Sans Mono": {
		"normal": "aurulent/aurulent.otf"
	}
}
```

Anyway, those are my thoughts. I guess it comes down to the question of wether it's still my repo ;) If it were me I'd like to try a few things (ie. 1 and 3) and see what that does. But I wouldn't be developing it for myself (Atom is too slow for the projects I work on) so I don't know if I'd actually do it.

**Comment by lierdakil** [comment]
As for 1, I've used post-install hook for generating grammar in atom-haskell/language-haskell for a while. I've seen quite a few issues related to that, and ultimately decided it's cheaper to keep everything checked into git.

For 3, I'll see what it leads to later today or tomorrow.

**Comment by braver** [comment]
I can see how running a generator on-install can be tricky. Properly handling all the events and invalidating caches etc. is a lot of head-ache. In general if you can run design time, you should. It's not pretty to check in the generated code, but alternatives for that aren't worth the effort for this project. 

If we're going to have a build step, we might as well go with yaml. I'm much happier to have a design time / build time dependency that in the runtime. Especially if it makes editing easier.

So, color me convinced. ⛵️ it :shipit: !

**Comment by braver** [comment]
I just thought of something you might have missed. Some fonts use ligatures, or should be rendered without antialiasing.

**Comment by lierdakil** [comment]
Sure, but neither `.no-smoothing()` nor `.ligatures()` from `functions.less` are actually used anywhere, as far as I could tell.

**Comment by braver** [comment]
Oh, I guess you’re right. 🤷🏼‍♂️

**Comment by lierdakil** [comment]
Okay, I'll merge this then. Kinda forgot about this.

**Pull request merged**
