### PR TITLE
adding the amazing IBM Plex Mono family

### PR DESCRIPTION
**Pull request by tabascoeye**
I added the IBM Plex Mono font because it is amazing.

Original source: https://github.com/IBM/plex/tree/master/IBM-Plex-Mono/fonts/complete/otf

### CODE REVIEW

**Comment by braver** [comment]
If you want to expose all the different weights you need to put them in the package json too. I find that usually that adds too much weight to the package, so I'd advise to remove the font files that aren't used.

**Comment by tabascoeye** [comment]
yeah I think so too. I thought I stick to what the other fonts look like and "Iosevka" also has 5 weights, each with italics and bold modifier.

I'll strip it down a bit.

**Comment by braver** [comment]
Oh, yeah, I'm super consistent like that. 🙄 Eh, anyway...

**Comment by tabascoeye** [comment]
should I modify the PR some more? Or are you cool with merging this?

**Comment by braver** [comment]
Oh, forgot to review it again, sorry. Cluld you lowercase the font files and folder? Makes it easier to automate stuff. Otherwise it looks good to go.

**Comment by tabascoeye** [comment]
what the frack. I just realized you already added IBM Plex under the name "plex" last year. Only there is no release after 3.0.3 to include them.
https://github.com/braver/fonts/commit/a8134b93c51122be5b70c74c2fd79ac64d0de065

So I guess you should release a 3.0.4 which will then include IBM plex already and my work here was for the bin m(

**Comment by braver** [comment]
Oh, that's embarrassing 😓 I don't actively keep track of this repo (super busy with other things) and it's finally caught up with me. I also don't use Atom anymore, so I do sometimes remember to publish releases for the plugins I still have for it, but I guess I forgot to do so here. I'm so sorry man.

**Pull request closed without merging**
